apiVersion: v1
kind: Service
metadata:
  name: {{ include "lwa.fullname" . }}
  labels:
    {{- include "lwa.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: {{ .Values.service.type }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: "80"
  selector:
    {{- include "lwa.selectorLabels" . | nindent 4 }}
